# Generated by Django 5.2.4 on 2025-10-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_loginattempt_accountlock_securitynotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreversal',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='main_application.payment'),
        ),
    ]
