# Generated by Django 5.2.4 on 2025-10-29 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_alter_paymentreversal_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreversal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
