# Generated by Django 5.2.4 on 2025-10-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_paymentreversal_approved_by_paymentreversal_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_number', models.CharField(max_length=50, unique=True)),
                ('reconciliation_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_payments', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reconciled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('discrepancy', 'Discrepancy Found'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.paymentmethod')),
                ('revenue_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_application.revenuestream')),
            ],
            options={
                'db_table': 'reconciliations',
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
    ]
